#if !canImport(ObjectiveC)
import XCTest

extension PaddingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PaddingTests = [
        ("testPadding", testPadding),
        ("testPaddingError", testPaddingError),
        ("testPaddingPredefined", testPaddingPredefined),
    ]
}

extension SodiumMemoryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SodiumMemoryTests = [
        ("testSodiumMemoryLargeAlloc", testSodiumMemoryLargeAlloc),
    ]
}

extension XchachaSivCoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XchachaSivCoderTests = [
        ("testXchachaSiv", testXchachaSiv),
        ("testXchachaSivError", testXchachaSivError),
    ]
}

extension XchachaSivTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XchachaSivTests = [
        ("testXchachaSiv", testXchachaSiv),
        ("testXchachaSivError", testXchachaSivError),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PaddingTests.__allTests__PaddingTests),
        testCase(SodiumMemoryTests.__allTests__SodiumMemoryTests),
        testCase(XchachaSivCoderTests.__allTests__XchachaSivCoderTests),
        testCase(XchachaSivTests.__allTests__XchachaSivTests),
    ]
}
#endif
