#if !canImport(ObjectiveC)
import XCTest

extension Blake2bTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Blake2bTests = [
        ("testBlake2b", testBlake2b),
    ]
}

extension SodiumMemoryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SodiumMemoryTests = [
        ("testSodiumMemoryLargeAlloc", testSodiumMemoryLargeAlloc),
    ]
}

extension XchachaSivTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XchachaSivTests = [
        ("testXchachaSiv", testXchachaSiv),
        ("testXchachaSivError", testXchachaSivError),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Blake2bTests.__allTests__Blake2bTests),
        testCase(SodiumMemoryTests.__allTests__SodiumMemoryTests),
        testCase(XchachaSivTests.__allTests__XchachaSivTests),
    ]
}
#endif
