#if !canImport(ObjectiveC)
import XCTest

extension SodiumMemoryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SodiumMemoryTests = [
        ("testSodiumMemoryLargeAlloc", testSodiumMemoryLargeAlloc),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SodiumMemoryTests.__allTests__SodiumMemoryTests),
    ]
}
#endif
