#if !canImport(ObjectiveC)
import XCTest

extension HkdfSha512Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HkdfSha512Tests = [
        ("testHkdfSha512", testHkdfSha512),
        ("testHkdfSha512Compare", testHkdfSha512Compare),
    ]
}

extension XchachaPolyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XchachaPolyTests = [
        ("testXchachaPoly", testXchachaPoly),
        ("testXchachaPolyError", testXchachaPolyError),
        ("testXchachaPolyPredefined", testXchachaPolyPredefined),
    ]
}

extension XchachaSivTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XchachaSivTests = [
        ("testXchachaSiv", testXchachaSiv),
        ("testXchachaSivError", testXchachaSivError),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HkdfSha512Tests.__allTests__HkdfSha512Tests),
        testCase(XchachaPolyTests.__allTests__XchachaPolyTests),
        testCase(XchachaSivTests.__allTests__XchachaSivTests),
    ]
}
#endif
