#if !canImport(ObjectiveC)
import XCTest

extension CipherXchachaPolyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CipherXchachaPolyTests = [
        ("testXchachaPoly", testXchachaPoly),
    ]
}

extension CipherXchachaSivTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CipherXchachaSivTests = [
        ("testXchachaSiv", testXchachaSiv),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CipherXchachaPolyTests.__allTests__CipherXchachaPolyTests),
        testCase(CipherXchachaSivTests.__allTests__CipherXchachaSivTests),
    ]
}
#endif
